config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :activities, only: [ :index, :show ] do
    resources :events, only: [ :create ]
  end
  resources :events, only: [ :update, :destroy ]
  resources :calendars, only: [ :show, :create ]
  resources :wish_lists, only: [:create, :show, :update]
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :events, dependent: :destroy
  has_one_attached :photo

  validates :title, :address, :description, :duration, presence: true
  validates :duration, numericality: { only_integer: true }
  validates :rating, inclusion: {in: (0..5)}
  validates :category, inclusion: {in: %w(sport culture gastronomie) }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :wish_list
  belongs_to :activity

  # validates :start_time, presence: true
  def self.assign_start_time(events)
    #events = self.all.to_a.sort_by(&:position)
    events.each_with_index do |event, index|
      # si c'est le 1er event on lui attribut le debut de la wish list (start_at)
      if index == 0
        event.start_time = event.wish_list.start_at + 10.hours
      else
        # si (heure démarrage event previous + (durée activity + 30 mn).formatminutes).récup heure est sup à 18h
        previous = events[index - 1]
        if previous.next_hour > 18
          # alors on ajoute 1 jour au démarrage de l'event précédent
          # et on lui attribut une heure de démarrage
          year = previous.start_time.year
          month = previous.start_time.month
          day = previous.start_time.day + 1
          event.start_time = DateTime.new(year, month, day, 10, 0)
        else
          # sinon on ajoute l'event suivant à la fin l'event précédant et des 30 mn de déplacement
          event.start_time = previous.next_slot
        end
      end
      event.save
    end
  end

  def next_hour
   return self.next_slot.hour + self.next_slot.min * 1.0/60
  end

  def next_slot
   self.start_time + (self.activity.duration + 30).minute
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :wish_list

  validates :nick_name, presence: true
  after_create :wish_list_creation

  def wish_list_creation
    WishList.create!(user: self)
  end
end

app/models/wish_list.rb
class WishList < ApplicationRecord
  belongs_to :user
  has_many :events

  validates :address, :radius, :start_at, :end_at, presence: true, on: :update
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  def index
    @wishlist = current_user.wish_list
    if params[:activity].present?
      @activities = Activity.near(params[:address],10)
    elsif params[:category]
      @activities = Activity.where(category: params[:category])
    else
      @activities = Activity.all
    end
    @markers = @activities.geocoded.map do |activity|
      {
        lat: activity.latitude,
        lng: activity.longitude,
        info_window: render_to_string(partial: "info_window", locals: { activity: activity })
      }
    end
  end

  def show
    @activity = Activity.find(params[:id])
    @event = Event.new
  end

  private

  def params_activity
    params.require(:activity).permit(:title, :category, :address, :description, :website_url, :duration, :rating, :photo)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nick_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:nick_name])
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  def create
    @events = current_user.wish_list.events.order(:start_time)
    Event.assign_start_time(@events)
    redirect_to calendar_path(1)
  end

  def show
    @events = current_user.wish_list.events
  end

  private

  def calendar_params
    params.require(:calendar).permit(:events)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def create
   @event = Event.new(activity_id: params[:activity_id])
   @event.wish_list = current_user.wish_list
   @event.start_time = Date.today
    if @event.save
      #redirect_to wish_list_path(current_user.wish_list)
      redirect_to activities_path
    else
      render 'activities/show'
    end
  end

  def update
    render json: { success: true }
    @event = Event.find(params[:id])
    @wish_list = @event.wish_list
    @events = @wish_list.events.order(:start_time).to_a
    @events.delete_at(params[:oldPosition].to_i)
    @events.insert(params[:newPosition].to_i, @event)
    Event.assign_start_time(@events)
    #redirect_to request.referrer
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to request.referrer
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @wishlist = current_user.wish_list
  end
end

app/controllers/wish_lists_controller.rb
class WishListsController < ApplicationController
  def update
    @wishlist = WishList.find(params[:id])
    if @wishlist.update(wishlist_params)
      redirect_to activities_path
    else
      render "pages/home"
    end
  end

  private

  def wishlist_params
    params.require(:wish_list).permit(:address, :radius, :start_at, :end_at)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/activities/_info_window.html.erb
<h2><%= activity.title %></h2>
<p><%= activity.address %></p>

app/views/activities/index.html.erb
<div class="banner-gradiant">
  <div class="container">
    <div class="home-form-content">
      <%= simple_form_for(@wishlist, method: :patch, url: wish_list_path(@wishlist)) do |f| %>
        <div class="form-input">
          <div class="form-input-location">
            <%= f.input :address, placeholder: 'Entrez une adresse ici', label: false, id: 'address' %>
            <%= f.input :radius, placeholder: 'Rayon', label: false %>
          </div>
          <div class="form-input-dates">
            <%= f.input :start_at, as: :date, html5: true, label: false %>
            <%= f.input :end_at, as: :date, html5: true, label: false %>
          </div>
        </div>

        <div class="form-action">
          <%= f.submit "Lancer une nouvelle recherche", id: "btn-gradiant" %>
        </div>

        <div class="filter">
            <% Activity.all.map(&:category).uniq.each do |category| %>
            <%= link_to category, activities_path(params: { category: category }), id: "btn-gradiant" %>
            <% end %>
            <%= link_to "Toutes", activities_path, id: "btn-gradiant" %>
        </div>
      <% end %>
    </div>
  </div>

</div>

<div class="container">
  <div class="activities-container">
    <div class="activities-cards">
      <% @activities.each do |activity| %>
        <div class="card-activity">

          <div class="card-img">
            <%= cl_image_tag activity.photo.try(:key) %>
            <p><%= activity.category %></p>
          </div>

          <div class="card-activity-infos">
            <h2><%= activity.title %></h2>
            <p><%= activity.address %></p>

            <div class="card-activity-infos-bottom">
              <p class="card-activity-infos-bottom-rating">
                <% activity.rating.times do %>
                  <i class="fas fa-star"></i>
                <% end %>
              </p>
              <p><%= activity.price %>€</p>
            </div>
            <%= link_to 'plus', activity_path(activity), id: 'btn-gradiant' %>
          </div>
        </div>
      <% end %>
    </div>

     <div id="map"
        style="width: 100%; height: 100vh;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    </div>

  </div>
</div>

app/views/activities/show.html.erb
<!-- <div class="container">
  <div class="activity-content">
    <div class="activity-card">
      <h2><%= @activity.title %></h2>
      <div class="activity-infos">
        <p class="activity-stars"><% @activity.rating.times do %>
          <i class="fas fa-star star-yellow"></i>
        <% end %></p>
        <p><%= @activity.category %></p>
      </div>
      <%= cl_image_tag @activity.photo.key, width: 400, height: 300 %>
      <h2>A propos</h2>
      <p><%= @activity.description %></p>
      <%= link_to 'Retour à la liste', activities_path, id: "btn-gradiant" %>  
    </div>

    <div class="activity-infos-plus">
      <div class="website-activity">
        <h2>Infos pratiques</h2>
        <p>Bénéficiez de toutes les informations dont vous avez besoin en visitant allant <%= link_to 'visiter notre site', @activity.website_url, target: "_blank" %></i></p>
      </div>

      <div class="activity-duration">
        <h2>Durée</h2>
        <p>La durée de cette activité est d'environ <%= @activity.duration/60 %> heures.</p>
      </div>

      <div class="activity-price">
        <h2>Coût moyen</h2>
        <p>Il faut compter un montant moyen de <%= @activity.price %> € pour cette activité.</p>
      </div>

      <%= simple_form_for [@activity, @event], method: :post do |f| %>
        <%= f.submit "Ajouter", data: { confirm: "Vous avez ajouté #{@activity.title} à votre Wish List"}, id: "btn-gradiant" %>
      <% end %>

    </div>
  </div>
</div> -->

<div class="container">
  <div class="activity-card">
    <%= cl_image_tag @activity.photo.key %>

    <div class="right-arrow-btn">
      <%= link_to activities_path do %>
        <i class="far fa-arrow-alt-circle-left"></i>
      <% end %>
    </div>

    <div class="activity-informations">
      <h2><%= @activity.title %></h2>
      <p><%= @activity.description %></p>

      <p class="activity-stars"><% @activity.rating.times do %>
        <i class="fas fa-star star-yellow"></i>
      <% end %></p>

      <p><i class="fas fa-map-signs" id="icons"></i> Address : <%= @activity.address %></p>

      <p><i class="fas fa-stopwatch" id="icons"></i> Durée : <%= @activity.duration/60 %> heure(s)</p>
      <p><i class="fas fa-hand-holding-usd" id="icons"></i> Prix : <%= @activity.price %> €</p>
      <p><i class="fas fa-paper-plane" id="icons-site"></i> <%= link_to 'Visiter le site', @activity.website_url, target: "_blank" %></p>

      <%= simple_form_for [@activity, @event], method: :post do |f| %>
        <%= f.submit "Ajouter à ma wishlist", data: { confirm: "Vous avez ajouté #{@activity.title} à votre Wish List"}, id: "btn-gradiant" %>
      <% end %>
    </div>
  </div>
</div>

app/views/calendar/show.html.erb
<!-- CALENDAR NOTIF -->
<div class="container">
  <div class="cenlendar-content">
    <% if current_user.wish_list.events.empty? %>
      <h1 class="calendar-empty-message">Votre wishlist est vide, veuillez d'abord ajouter des activités avant de générer votre calendrier</h1>
    <% else %>
      <h1><%= t("date.month_names")[(current_user.wish_list.start_at + 0.month).month].upcase %> - <%= Time.now.year %></h1>
      <div class="days-columns">
        <h2><%= t("date.day_names")[(current_user.wish_list.start_at + 0.day).wday].upcase %></h2>
        <h2><%= t("date.day_names")[(current_user.wish_list.end_at + 0.day).wday].upcase %></h2>
      </div>
    <% end %>

    <ul id="results">
      <% @events.sort_by(&:created_at).each do |event| %>
          <li data-event-id="<%= event.id %>">
            <div class="day-information">
              <div class="day-now"> 
                <%= current_user.wish_list.start_at.day %>
              </div>
              <div class="month-now">
                <%= t("date.abbr_month_names")[(current_user.wish_list.start_at + 0.month).month].upcase %>
              </div>
            </div>

            <div class="event-calendar-informations">
              <h2><%= event.activity.title.upcase %></h2>

              <div class="event-calendar-informations-inline">
                <div class="event-calendar-duration">
                  <i class="fas fa-stopwatch"></i>
                  <p><%= event.activity.duration/60 %>h</p>
                </div>
                <div class="event-calendar-address">
                  <i class="fas fa-map-marker-alt"></i>
                  <p><%= event.activity.address %></p>
                </div>
              </div>
            </div>
          </li>
        <% end %>
    </ul>
    
  </div>
</div>

app/views/calendars/show.html.erb
<!-- CALENDAR NOTIF -->
<div class="banner-gradiant">
  <div class="container">
    <h1>Mon calendrier d'activités</h1>
  </div>
</div>

<div class="container">
  <div class="cenlendar-content">

    <% if current_user.wish_list.events.empty? %>
      <h1 class="calendar-empty-message">Votre wishlist est vide, veuillez d'abord ajouter des activités avant de générer votre calendrier</h1>
        
    <% else %>
      <h1><%= t("date.month_names")[(current_user.wish_list.start_at + 0.month).month].upcase %> - <%= Time.now.year %></h1>

      <div class="days-columns">

        <div class="day-one">
          <h2><%= t("date.day_names")[(current_user.wish_list.start_at + 0.day).wday].upcase %></h2>
          <ul id="results1">
            <% @events.sort_by(&:start_time).group_by{|event| event.start_time.day }.each do |day, events| %>
              <% events.each do |event| %>
                <% if event.start_time.day == current_user.wish_list.start_at.day %>
                  <li data-event-id="<%= event.id %>">
                    <div class="day-information">
                      <div class="day-now">
                        <%= event.start_time.day %>
                      </div>
                      <div class="month-now">
                        <%= t("date.abbr_month_names")[(event.start_time + 0.month).month].upcase %>
                      </div>
                    </div>
                    <div class="event-calendar-informations">
                      <h2><%= event.activity.title.upcase %></h2>
                      <div class="event-calendar-informations">
                        <div class="event-calendar-duration">
                          <i class="fas fa-stopwatch"></i>
                          <p><%= event.start_time.strftime('%H:%M') %> à <%= event.start_time.hour + event.activity.duration/60 %>:<%= event.start_time.strftime('%M') %></p>
                        </div>
                        <div class="event-calendar-address">
                          <i class="fas fa-map-marker-alt"></i>
                          <p><%= event.activity.address %></p>
                        </div>
                      </div>
                    </div>
                  </li>
                <% end %>
              <% end %>
            <% end %>
          </ul>
        </div>

        <div class="day-two">
          <h2><%= t("date.day_names")[(current_user.wish_list.start_at + 1.day).wday].upcase %></h2>
          <ul id="results2">
            <% @events.sort_by(&:start_time).group_by{|event| event.start_time.day }.each do |day, events| %>
              <% events.each do |event| %>
                <% if event.start_time.day == current_user.wish_list.end_at.day %>
                  <li data-event-id="<%= event.id %>">
                    <div class="day-information">
                      <div class="day-now">
                        <%= event.start_time.day %>
                      </div>
                      <div class="month-now">
                        <%= t("date.abbr_month_names")[(event.start_time + 0.month).month].upcase %>
                      </div>
                    </div>
                    <div class="event-calendar-informations">
                      <h2><%= event.activity.title.upcase %></h2>
                      <div class="event-calendar-informations">
                        <div class="event-calendar-duration">
                          <i class="fas fa-stopwatch"></i>
                          <p><%= event.start_time.strftime('%H:%M') %> à <%= event.start_time.hour + event.activity.duration/60 %>:<%= event.start_time.strftime('%M') %></p>
                        </div>
                        <div class="event-calendar-address">
                          <i class="fas fa-map-marker-alt"></i>
                          <p><%= event.activity.address %></p>
                        </div>
                      </div>
                    </div>
                  </li>
                <% end %>
              <% end %>
            <% end %>
          </ul>
        </div>

      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventpik | Planifier vos activités</title>
    <meta name="description" content="<%= meta_description %>">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!-- Favicon -->
    <%= favicon_link_tag "favicon.png" %>
  
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/wishlist' if current_user %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<!-- pages#home BANNER -->
<div class="banner">
  <!-- SIMPLE_FORM_FOR -->
  <div class="container">
    <div class="home-description">
      <h1> Planifier vos activités</h1>
      <p>Grâce à <strong>Eventpik</strong> trouvez les meilleures activités près de chez vous en quelques cliques et ajoutez les à votre calendrier personnel. Pour cela rien de plus simple, remplissez les champs ci-dessous lancez la recherche et laissez vous guider !</p>
    </div>
    <div class="home-form-content">
      <%= simple_form_for(@wishlist, method: :patch, url: wish_list_path(@wishlist)) do |f| %> 
        <div class="form-input">
          <div class="form-input-location">
            <%= f.input :address, placeholder: 'Entrez une adresse ici', label: false, id: 'address' %>
            <%= f.input :radius, placeholder: 'Rayon', label: false %>
          </div>
          <div class="form-input-dates">
            <%= f.input :start_at, as: :date, html5: true, label: false %>
            <%= f.input :end_at, as: :date, html5: true, label: false %>
          </div>
        </div>

        <div class="form-action">
          <%= f.submit "Lancer la recherche", id: "btn-gradiant" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- Footer -->
<div class="footer-dark">
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-sm-6 col-md-3 item">
          <h3>Services</h3>
          <ul>
            <li><a href="#">Web design</a></li>
            <li><a href="#">Dévelopement</a></li>
            <li><a href="#">Hébergement</a></li>
          </ul>
        </div>
        <div class="col-sm-6 col-md-3 item">
          <h3>A propos</h3>
          <ul>
            <li><a href="#">Compagnie</a></li>
            <li><a href="#">Equipe</a></li>
            <li><a href="#">Carrières</a></li>
          </ul>
        </div>
        <div class="col-md-6 item text">
          <h3>Eventpik</h3>
          <p><i class="fas fa-map-marker-alt"></i> BORDEAUX, CP 33 000, France</p>
          <p><i class="fas fa-envelope"></i> contact@eventpik.xyz</p>
          <p><i class="fas fa-phone"></i> 05 56 25 25 25</p>
          <p><i class="fas fa-fax"></i> 05 56 25 25 26</p>
        </div>
        <div class="col item social">
          <a href="#"><i class="fab fa-facebook"></i></a>
          <a href="#"><i class="fab fa-twitter"></i></a>
          <a href="#"><i class="fab fa-snapchat-ghost"></i></a>
          <a href="#"><i class="fab fa-instagram"></i></a>
        </div>
      </div>
      <p class="copyright">Eventpik © 2018</p>
    </div>
  </footer>
</div>

app/views/shared/_navbar.html.erb
<div class="top-navbar">
  <div class="container">
    <div class="top-navbar-content">
      <%= link_to 'EVENTPIK', root_path, class: 'top-navbar-logo' %>
      <div class="top-navbar-menu">
        <ul>
          <% if user_signed_in? %>
            <li class="top-navbar-item">
              <% if current_user.wish_list.events.empty? %>
                <%#= link_to "Ma wishlist", wish_list_path(current_user.wish_list), id: 'wishlist-menu'%>
                <p id='wishlist-menu'>Ma wishlist</p>
              <% else %>
                <p id='wishlist-menu'>Ma wishlist</p>
                <div class="events-count">
                  <%= "#{current_user.wish_list.events.count}" %>
                </div>
              <% end %>
            </li>
            <li class="top-navbar-item">
              <%= link_to "Mon calendrier", calendar_path(1) %>
            </li>
            <li class="top-navbar-item">
              <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete %>
            </li>
          <% else %>
            <li class="top-navbar-item">
              <%= link_to "Se connecter", new_user_session_path %>
            </li>

            <li class="top-navbar-item">
              <%= link_to "S'inscrire",  new_user_registration_path, id: "btn-gradiant" %>
            </li>
          <% end %>
        </ul>
      </div>   
    </div>
  </div>
</div>

app/views/shared/_wishlist.html.erb
<div class="wishlist-content">
  <div class="wishlist-menu-top">
    <div class="wishlist-menu-top-right">
      <h1>Ma wishlist</h1>
      <div class="wishlist-menu-events-count">
        <%= "#{current_user.wish_list.events.count}" %>
      </div>
    </div>

    <div class="close-wishlist-btn" id='cross-btn'>
      <i class="far fa-times-circle" ></i>
    </div>
  </div>

  <div class="events-list-notifications">
    <% if current_user.wish_list.events.empty? %>
      <p class="empty-message"><%= "Votre wishlist est actuellement vide" %></p>

    <% else %>
      <p class="empty-message"><%= "Votre wishlist comporte actuellement (#{current_user.wish_list.events.count}) évènement(s)" %></p>
      <% current_user.wish_list.events.each do |event| %>
        <div class="event-notification">
          <div class="event-notification-info">
            <h2><%= event.activity.title %></h2>
            <h3><%= current_user.wish_list.address %></h3>
            <% if current_user.wish_list.start_at && current_user.wish_list.start_at %>
              <p>Du <%= current_user.wish_list.start_at.strftime('%D') %> au <%= current_user.wish_list.end_at.strftime('%D') %></p>
            <% end %>
          </div>
          <%= link_to event_path(event), method: :delete, data: { confirm: "Voulez-vous vraiment supprimer #{event.activity.title.upcase} de votre wishlist ?" } do %>
            <i class="far fa-trash-alt"></i></a>
          <% end %>
        </div>
      <% end %>
    <% end %>
    <%= link_to "générer mon calendrier", calendars_path, method: :post, id: "btn-gradiant" %>
  </div>
</div>

app/views/wish_lists/update.html.erb
<h1>WishLists#update</h1>
<p>Find me in app/views/wish_lists/update.html.erb</p>